== NPCs

[#Gundren]
=== Gundren Rockseeker

Cousin of Kildrak. Gundren and his two brothers apearently have found the lost <<Wave Echo Cave>>, a mine of tremendous resources and magic. He has contracted you to get goods to <<Phandalin>> but in his transit over, he got hijacked and taken. His location is unknown but guessed as <<Cragmaw Castle>>.

=== Droop

Droop is a goblin that follows the party since they rescued him in <<Phandalin>> from <<Glasstaff>>.
Tends to faint in battles.

[#Sildar]
=== Sildar Hallwinter

Agent of the <<Lords' Alliance>>. Rescued by the party at <<Cragmaw Hideout>>. Has his seat at the Townhall in <<Phandalin>> and wants <<Gundren>> saved to open the lost mines again.

[#Glasstaff]
=== Iarno "Glasstaff" Albrek

Occupied the <<Tresendar Manor>> with a gang of local thugs (the <<Redbrands>>). Was captured by the party there and given to the <<Phandalin>> officials, who brought him to the authorities in <<Waterdeep>>. Was sentenced to death there. Had a note from <<The Blackspider>>.

=== The Blackspider

An unknown entity. <<Glasstaff>> had a note from them and the party found a wanted poster from a goblinoid hunting group that ambushed the party.

=== Ragalof

Hermit currently living in <<Thundertree>> and studiying the landscape. Is annoyed by the <<Chromatic Dragon in Thundertree>>. And has noticed that recently a <<dragoncult-thundertree,cult>> moved to <<Thundertree>>

=== Chromatic Dragon in Thundertree

Supposedly a green dragon.

[#dragoncult-thundertree]
=== Dragon Cult in Thundertree

Not much known is about them. They worship the <<Chromatic Dragon in Thundertree,Chromatic Dragon>>. They seem to have a good amount of dragon in them.
